
services:
  # PostgreSQL Database
  postgres:
    image: postgres:18
    restart: always
    container_name: user_management_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - user_management_db_data:/var/lib/postgresql
      - ./backups:/backups
    networks:
      - backend

  # # Node.js Application
  # app:
  #   build: .
  #   restart: always
  #   container_name: user_management_app
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - PORT=${PORT}
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - REFRESH_SECRET=${REFRESH_SECRET}
  #   ports:
  #     - "${PORT}:3000"
  #   volumes:
  #     - ./backups:/app/backups
  #   depends_on:
  #     - postgres
  #   networks:
  #     - backend

volumes:
  user_management_db_data:

networks:
  backend: